// packages/svelte/src/LazyYoutubePlayer.svelte
<script>
  import { onMount } from 'svelte';
  import { LazyYoutubePlayer } from '../core/index.js';

  export let videoId;

  let ytContainer;

  onMount(() => {
    if (ytContainer) {
      new LazyYoutubePlayer(ytContainer, videoId);
    }
  });
</script>

<div bind:this={ytContainer} class="NexosYt" data-embed={videoId}></div>

<style src="../core/style.css"></style>

// packages/vue/src/LazyYoutubePlayer.vue
<template>
  <div ref="ytContainer" class="NexosYt" :data-embed="videoId"></div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { LazyYoutubePlayer } from '../core/index.js';

const props = defineProps({
  videoId: {
    type: String,
    required: true
  }
});

const ytContainer = ref(null);

onMounted(() => {
  if (ytContainer.value) {
    new LazyYoutubePlayer(ytContainer.value, props.videoId);
  }
});
</script>

<style src="../core/style.css"></style>
